require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'examples/**/*'

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes

Layout/LineLength:
  Max: 120

Metrics/ClassLength:
  Exclude:
    - 'lib/astroapi/categories/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'

Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'spec/**/*'
    - 'lib/astroapi/validators/**/*'
    - 'lib/astroapi/http/client.rb'
    - 'lib/astroapi/client.rb'

Metrics/AbcSize:
  Max: 20
  Exclude:
    - 'spec/**/*'
    - 'lib/astroapi/validators/**/*'
    - 'lib/astroapi/error.rb'
    - 'lib/astroapi/http/client.rb'
    - 'lib/astroapi/client.rb'

RSpec/ExampleLength:
  Max: 15

RSpec/MultipleExpectations:
  Max: 5

RSpec/NestedGroups:
  Max: 4

RSpec/FilePath:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/StubbedMock:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - 'spec/integration/**/*'

Naming/AccessorMethodName:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 15
  Exclude:
    - 'lib/astroapi/validators/**/*'
    - 'lib/astroapi/error.rb'

Metrics/PerceivedComplexity:
  Max: 15
  Exclude:
    - 'lib/astroapi/validators/**/*'
    - 'lib/astroapi/error.rb'
